<table id="notfound-404-table" border="0">
    <tbody>    
        <tr height="95%" align="center">
            <td style="background: no-repeat center/100% url('/img/doge-404.jpeg');" >
            </td>
        </tr>
        <tr height="auto" align="center">
            <td>
                <h1>404</h1>
                <p>Page not found!</p>
            </td>
        </tr>
    </tbody>
</table>
